package com.yongle.letuiweipad.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yongle.letuiweipad.domain.createorder.GoodBean;
import com.yongle.letuiweipad.domain.goodinfo.GoodsTypeInfo;

import com.yongle.letuiweipad.dao.GoodBeanDao;
import com.yongle.letuiweipad.dao.GoodsTypeInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig goodBeanDaoConfig;
    private final DaoConfig goodsTypeInfoDaoConfig;

    private final GoodBeanDao goodBeanDao;
    private final GoodsTypeInfoDao goodsTypeInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        goodBeanDaoConfig = daoConfigMap.get(GoodBeanDao.class).clone();
        goodBeanDaoConfig.initIdentityScope(type);

        goodsTypeInfoDaoConfig = daoConfigMap.get(GoodsTypeInfoDao.class).clone();
        goodsTypeInfoDaoConfig.initIdentityScope(type);

        goodBeanDao = new GoodBeanDao(goodBeanDaoConfig, this);
        goodsTypeInfoDao = new GoodsTypeInfoDao(goodsTypeInfoDaoConfig, this);

        registerDao(GoodBean.class, goodBeanDao);
        registerDao(GoodsTypeInfo.class, goodsTypeInfoDao);
    }
    
    public void clear() {
        goodBeanDaoConfig.clearIdentityScope();
        goodsTypeInfoDaoConfig.clearIdentityScope();
    }

    public GoodBeanDao getGoodBeanDao() {
        return goodBeanDao;
    }

    public GoodsTypeInfoDao getGoodsTypeInfoDao() {
        return goodsTypeInfoDao;
    }

}
